/**
 * Dashboard constants
*/
// export const DASHBOARD_REQUEST_REQUEST = 'DASHBOARD_REQUEST_REQUEST';
// export const DASHBOARD_REQUEST_SUCCESS = 'DASHBOARD_REQUEST_SUCCESS';
// export const DASHBOARD_REQUEST_FAIL = 'DASHBOARD_REQUEST_FAIL';

export const PULL_REQUEST_REQUEST = 'PULL_REQUEST_REQUEST';
export const PULL_REQUEST_SUCCESS = 'PULL_REQUEST_SUCCESS';
export const PULL_REQUEST_FAIL = 'PULL_REQUEST_FAIL';

export const COMMITS_REQUEST_REQUEST = 'COMMITS_REQUEST_REQUEST';
export const COMMITS_REQUEST_SUCCESS = 'COMMITS_REQUEST_SUCCESS';
export const COMMITS_REQUEST_FAIL = 'COMMITS_REQUEST_FAIL';