/**
 * commits constants
*/

export const COMMITS_REQUEST_REQUEST = 'COMMITS_REQUEST_REQUEST';
export const COMMITS_REQUEST_SUCCESS = 'COMMITS_REQUEST_SUCCESS';
export const COMMITS_REQUEST_FAIL = 'COMMITS_REQUEST_FAIL';