/**
 * comments data constants
*/

export const COMMENTS_REQUEST_REQUEST = 'COMMENTS_REQUEST_REQUEST';
export const COMMENTS_REQUEST_SUCCESS = 'COMMENTS_REQUEST_SUCCESS';
export const COMMENTS_REQUEST_FAIL = 'COMMENTS_REQUEST_FAIL';
